### ISSUE TITLE
Fails functional tests

### ISSUE THREAD

**Issue by nicksc423** [vfarcic/go-demo-3#8]
This current build fails when we run the functional tests.  I got the following commands from the following gist you wrote: https://gist.github.com/vfarcic/4edc53d5dd11814651485c9ff3672fb7

sh "go get -d -v -t"

sh """go test ./... -v \
   --run FunctionalTest"""

Error was:

```
+ go test ./... -v --run FunctionalTest
# _/home/jenkins/workspace/Build_Test_Release
./main.go:144:9: undefined: prometheus.Handler
FAIL    _/home/jenkins/workspace/Build_Test_Release [build failed]
```

I solved this issue by referencing this documentation:
https://godoc.org/github.com/prometheus/client_golang/prometheus

To solve I added "github.com/prometheus/client_golang/prometheus/promhttp" to the import section in main.go

I then changed the **var prometheusHandler** function to be:

`var prometheusHandler = func() http.Handler {
	return promhttp.Handler()
}`

**Comment by vfarcic** [comment]
I think I know what the problem is.

I updated the repository by adding the `vendor` directory that contains specific versions of the libraries. So, even though Prometheus changed it's API, using the older version should still work. However, the issue is that the Gist you mentioned uses the old version of `golang` that does not support vendor dir. I just updated the Gist to use `golang:1.12` (it was `1.9` before). Can you try it again using the updated Gist?

**Comment by nicksc423** [comment]
Hey!

Sorry for the delay, I have been incredibly sick for the past two weeks so I was unable to read your response!  This does fix the issue!  Thanks!!
